<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>__MCA_TFM__</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);NU1608;NU1510</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MinimalCleanArch" Version="__MCA_VERSION__" />
    <!--#if (UseValidation)-->
    <PackageReference Include="MinimalCleanArch.Validation" Version="__MCA_VERSION__" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <!--#endif-->
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.5" />
    <!--#if (UseCaching)-->
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.5" />
    <!--#endif-->
    <!--#if (UseAuth)-->
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.5" />
    <!--#endif-->
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <!--#if (UseCaching)-->
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.3" />
    <!--#endif-->
    <!--#if (UseAuth)-->
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.3" />
    <!--#endif-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MCA.Domain\MCA.Domain.csproj" />
  </ItemGroup>

</Project>
